
import { SearchResult } from "./types";

export const mockResults: SearchResult[] = [
  {
    id: "1",
    txId: "OP-TX-001",
    vesselName: "Vessel Alpha",
    tradeType: "Import",
    productType: "Crude",
    productName: "Crude Oil",
    buyer: "Company A",
    supplier: "Supplier X",
    layDayStart: "01-Apr-2023",
    loadPort: "Singapore",
    dischargePort: "Hong Kong",
    quantityLoadedBBLs: "14,750",
    quantityLoadedMT: "2,350",
    status: "Updated",
  },
  {
    id: "2",
    txId: "OP-TX-002",
    vesselName: "Vessel Beta",
    tradeType: "Export",
    productType: "Refined",
    productName: "Diesel",
    buyer: "Company B",
    supplier: "Supplier Y",
    layDayStart: "10-Apr-2023",
    loadPort: "Hong Kong",
    dischargePort: "Tokyo",
    quantityLoadedBBLs: "8,050",
    quantityLoadedMT: "1,280",
    status: "Draft",
  },
  {
    id: "3",
    txId: "OP-TX-003",
    vesselName: "Vessel Gamma",
    tradeType: "Domestic",
    productType: "Gas",
    productName: "LNG",
    buyer: "Company C",
    supplier: "Supplier Z",
    layDayStart: "18-Apr-2023",
    loadPort: "Shanghai",
    dischargePort: "Busan",
    quantityLoadedBBLs: "12,300",
    quantityLoadedMT: "1,950",
    status: "Final",
  },
];
